"use client";
import { useRef, useState } from "react";
import { FileSpreadsheet, UploadCloud } from "lucide-react";
import { read, utils } from "xlsx";
import { PageHeader } from "@/components/PageHeader";
import { useWords } from "@/hooks/useWords";
import { JLPT_LEVELS, type JLPTLevel, type WordInput } from "@/types";

type Parsed = { row: number; data?: WordInput; errors: string[]; raw: Record<string, unknown> };
const normalize = (row: Record<string, unknown>) => Object.fromEntries(Object.entries(row).map(([k,v]) => [k.trim().toLowerCase().replace(/[ _-]/g,""),v]));
function parseRows(rows: Record<string, unknown>[]): Parsed[] { return rows.map((raw, index) => { const r=normalize(raw); const errors:string[]=[]; const level=String(r.level??"").trim().toUpperCase(); const day=Number(r.day); const kanji=String(r.kanji??"").trim(); const reading=String(r.reading??"").trim(); const english=String(r.english??"").trim(); if(!JLPT_LEVELS.includes(level as JLPTLevel)) errors.push("Level must be N5–N1"); if(!Number.isInteger(day)||day<1) errors.push("Day must be a positive number"); if(!kanji) errors.push("Kanji is required"); if(!reading) errors.push("Reading is required"); if(!english) errors.push("English is required"); return {row:index+2,raw,errors,data:errors.length?undefined:{level:level as JLPTLevel,day,kanji,reading,english,partOfSpeech:String(r.partofspeech??"").trim(),example:String(r.example??"").trim(),notes:String(r.notes??"").trim()}}; }); }
export default function ImportPage(){const{importWords}=useWords();const input=useRef<HTMLInputElement>(null);const[parsed,setParsed]=useState<Parsed[]>([]);const[fileName,setFileName]=useState("");const[drag,setDrag]=useState(false);const[busy,setBusy]=useState(false);const[progress,setProgress]=useState(0);const[message,setMessage]=useState("");const[error,setError]=useState("");
async function load(file?:File){if(!file)return;setError("");setMessage("");if(!/\.(csv|xlsx)$/i.test(file.name)){setError("Choose a .csv or .xlsx file.");return}try{const buffer=await file.arrayBuffer();const workbook=read(buffer,{type:"array"});const sheet=workbook.Sheets[workbook.SheetNames[0]];const rows=utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""});if(!rows.length)throw new Error();setParsed(parseRows(rows));setFileName(file.name)}catch{setError("This file could not be read. Check that it is a valid CSV or Excel workbook with a header row.")}}
const valid=parsed.filter(r=>r.data).map(r=>r.data!);async function confirm(){try{setBusy(true);setProgress(0);await importWords(valid,n=>setProgress(n));setMessage(`${valid.length} words imported successfully. Existing study progress was preserved.`);setParsed([]);setFileName("")}catch{setError("The import could not be saved. Check your network connection and Firestore permissions.")}finally{setBusy(false)}}
return <><PageHeader eyebrow="Add vocabulary" title="Import your study list" description="CSV and Excel files are parsed safely in your browser."/><section className="panel"><div className={`dropzone ${drag?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);load(e.dataTransfer.files[0])}}><UploadCloud size={36}/><h3>Drop your vocabulary file here</h3><p className="hint">.csv or .xlsx · Required: level, day, kanji, reading, english</p><button className="btn secondary" onClick={()=>input.current?.click()}>Choose a file</button><input ref={input} type="file" accept=".csv,.xlsx" onChange={e=>load(e.target.files?.[0])}/></div>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="pill good">✓ {message}</p>}{parsed.length>0&&<><div className="preview-summary"><span className="pill"><FileSpreadsheet size={14}/>{fileName}</span><span className="pill good">✓ {valid.length} valid</span><span className="pill bad">{parsed.length-valid.length} invalid</span></div><div className="table-wrap"><table><thead><tr><th>Row</th><th>Level</th><th>Day</th><th>Kanji</th><th>Reading</th><th>English</th><th>Validation</th></tr></thead><tbody>{parsed.slice(0,100).map(r=><tr key={r.row} className={r.errors.length?"invalid-row":""}><td>{r.row}</td><td>{r.data?.level??String(normalize(r.raw).level??"")}</td><td>{r.data?.day??String(normalize(r.raw).day??"")}</td><td>{r.data?.kanji??String(normalize(r.raw).kanji??"")}</td><td>{r.data?.reading??String(normalize(r.raw).reading??"")}</td><td>{r.data?.english??String(normalize(r.raw).english??"")}</td><td>{r.errors.join(" · ")||"Ready"}</td></tr>)}</tbody></table></div>{busy&&<div style={{marginTop:16}}><div className="progress"><div style={{width:`${valid.length?progress/valid.length*100:0}%`}}/></div><p className="hint">Saving {progress} of {valid.length}…</p></div>}<div className="form-actions"><button className="btn secondary" disabled={busy} onClick={()=>setParsed([])}>Cancel</button><button className="btn" disabled={busy||!valid.length} onClick={confirm}>{busy?"Importing…":`Import ${valid.length} words`}</button></div></>}</section><div className="panel" style={{marginTop:18}}><h3 style={{marginTop:0}}>Expected columns</h3><p className="hint">Column names are case-insensitive. Optional columns: partOfSpeech, example, notes. Re-importing the same level + day + kanji + reading updates its content without resetting study history.</p><a href="/sample-vocabulary.csv" download className="btn secondary">Download sample CSV</a></div></>}
